-- ============================================================
-- Vera Desarrollos — Etapa 6: 3D y multimedia + Cámaras
-- Pegá TODO esto en el SQL Editor de Supabase y ejecutá.
-- ============================================================
create table if not exists media (
  id          bigint generated by default as identity primary key,
  project_id  bigint references projects(id) on delete cascade,
  kind        text,      -- link | image | video
  title       text,
  url         text,      -- para links (Sketchfab, YouTube, Matterport...)
  file_path   text,      -- para imágenes / videos subidos
  mime        text,
  note        text,
  uploaded_by text,
  date        date,
  created_at  timestamptz default now()
);
alter table media enable row level security;
drop policy if exists "acceso logueados" on public.media;
create policy "acceso logueados" on public.media for all to authenticated using (true) with check (true);

create table if not exists cameras (
  id          bigint generated by default as identity primary key,
  project_id  bigint references projects(id) on delete cascade,
  name        text,
  url         text,
  type        text default 'auto',   -- auto | youtube | hls | image | video | iframe
  created_at  timestamptz default now()
);
alter table cameras enable row level security;
drop policy if exists "acceso logueados" on public.cameras;
create policy "acceso logueados" on public.cameras for all to authenticated using (true) with check (true);
