-- ============================================================
-- Vera Desarrollos — Etapa 4: Planos (categorías + revisiones)
-- Pegá TODO esto en el SQL Editor de Supabase y ejecutá.
-- ============================================================
create table if not exists plans (
  id          bigint generated by default as identity primary key,
  project_id  bigint references projects(id) on delete cascade,
  category    text,              -- general / estructural / eléctrico / pluvial / ...
  name        text,              -- nombre del plano (agrupa sus revisiones)
  revision    text default 'R0', -- R0, R1, R2...
  status      text default 'en revisión',  -- en revisión / aprobado / obsoleto
  current     boolean default true,        -- revisión vigente
  uploaded_by text,              -- quién lo subió
  file_path   text,
  mime        text,
  date        date,
  note        text,
  created_at  timestamptz default now()
);
alter table plans enable row level security;
drop policy if exists "acceso logueados" on public.plans;
create policy "acceso logueados" on public.plans for all to authenticated using (true) with check (true);
