-- ============================================================
-- Vera Desarrollos — Etapa 3
-- Liquidaciones (mano de obra) + factura en cada gasto.
-- Pegá TODO esto en el SQL Editor de Supabase y ejecutá.
-- ============================================================

-- ── Tabla de liquidaciones (pagos de mano de obra) ─────────
create table if not exists liquidaciones (
  id         bigint generated by default as identity primary key,
  worker     text not null,     -- persona o cuadrilla
  trade      text,              -- oficio (electricista, albañil, arquitecto...)
  amount     numeric default 0,
  date       date,
  project    text,
  note       text,
  created_at timestamptz default now()
);

alter table liquidaciones enable row level security;
drop policy if exists "acceso logueados" on public.liquidaciones;
create policy "acceso logueados" on public.liquidaciones for all to authenticated using (true) with check (true);

-- ── Factura (archivo) en cada gasto ────────────────────────
alter table expenses add column if not exists file_path text;
alter table expenses add column if not exists mime text;
