-- ============================================================
-- Vera Desarrollos — Etapa 5: Presupuestos de proveedores
-- Pegá TODO esto en el SQL Editor de Supabase y ejecutá.
-- (Las fotos en actualizaciones, la proyección de inversores y el
--  editar registros NO necesitan cambios en la base.)
-- ============================================================
create table if not exists budgets (
  id          bigint generated by default as identity primary key,
  provider_id bigint references providers(id) on delete cascade,
  name        text,               -- nombre del archivo
  concept     text,               -- concepto (ej. Aberturas) — sirve para comparar
  file_path   text,
  mime        text,
  amount      numeric default 0,
  date        date,
  project     text,
  status      text default 'pendiente',  -- pendiente / aprobado / rechazado
  note        text,
  created_at  timestamptz default now()
);
alter table budgets enable row level security;
drop policy if exists "acceso logueados" on public.budgets;
create policy "acceso logueados" on public.budgets for all to authenticated using (true) with check (true);
