-- ============================================================
-- Vera Desarrollos — Esquema de base de datos (Supabase)
-- Pegá TODO esto en el SQL Editor de tu proyecto de Supabase y ejecutá.
-- Las reglas de acceso (RLS) las agregamos en un segundo paso, según el
-- tipo de login que elijas (ver el chat).
-- ============================================================

-- ── Proyectos ──────────────────────────────────────────────
create table if not exists projects (
  id          bigint generated by default as identity primary key,
  name        text not null,
  address     text,
  status      text default 'planificacion',
  progress    int  default 0,
  start_date  date,
  end_date    date,
  sale_price  numeric default 0,
  budget      numeric default 0,
  spent       numeric default 0,
  description text,
  updates     jsonb default '[]'::jsonb,   -- historial de avances
  plans       jsonb default '[]'::jsonb,   -- planos (metadatos)
  model3d     text,
  stream_url  text,
  created_at  timestamptz default now()
);

-- ── Proveedores ────────────────────────────────────────────
create table if not exists providers (
  id         bigint generated by default as identity primary key,
  name       text not null,
  rubro      text,
  contact    text,
  phone      text,
  email      text,
  budgets    jsonb default '[]'::jsonb,     -- presupuestos (metadatos)
  created_at timestamptz default now()
);

-- ── Órdenes de compra (ítems embebidos como JSON) ──────────
create table if not exists orders (
  id         text primary key,             -- ej. OC-006
  provider_id bigint references providers(id) on delete cascade,
  project    text,
  date       date,
  status     text default 'pendiente',
  items      jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- ── Gastos ─────────────────────────────────────────────────
create table if not exists expenses (
  id         bigint generated by default as identity primary key,
  concept    text,
  category   text,
  amount     numeric default 0,
  date       date,
  provider   text,
  project    text,
  created_at timestamptz default now()
);

-- ── Inversiones / aportes ──────────────────────────────────
create table if not exists investments (
  id         bigint generated by default as identity primary key,
  investor   text not null,
  project    text,
  amount     numeric default 0,
  pct        numeric default 0,
  date       date,
  note       text,
  created_at timestamptz default now()
);

-- ── Comprobantes de proveedor ──────────────────────────────
-- El archivo (PDF/imagen) se guarda en Supabase Storage.
-- Acá guardamos solo los metadatos + la ruta al archivo.
create table if not exists receipts (
  id          bigint generated by default as identity primary key,
  provider_id bigint references providers(id) on delete cascade,
  name        text,
  file_path   text,        -- ruta dentro del bucket de Storage
  mime        text,
  amount      numeric default 0,
  date        date,
  project     text,
  order_id    text,
  note        text,
  created_at  timestamptz default now()
);

-- ── Documentos de inversor ─────────────────────────────────
create table if not exists investor_docs (
  id         bigint generated by default as identity primary key,
  investor   text not null,
  name       text,
  file_path  text,
  mime       text,
  kind       text,          -- contrato / recibo / etc.
  date       date,
  note       text,
  created_at timestamptz default now()
);

-- ── Seguridad a nivel de fila (RLS) ────────────────────────
-- La activamos ahora (por defecto bloquea todo hasta definir reglas).
-- No rompe nada: todavía no conectamos la app. Las políticas concretas
-- las agregamos según el login elegido.
alter table projects      enable row level security;
alter table providers     enable row level security;
alter table orders        enable row level security;
alter table expenses      enable row level security;
alter table investments   enable row level security;
alter table receipts      enable row level security;
alter table investor_docs enable row level security;
